name: CI-CD-Pipeline-AWS-BeansTalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-actions-demo-adv-it"
  EB_APPLICATION_NAME       : "flask"
  EB_ENVIRONMENT_NAME       : "flask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on:
  push:
    branches:
      - master
      
      
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
    - name: git clone repo
      uses: actions/checkout@v1


    - name: create ZIP deployment package
#archive deploy artifact exclude (-x) *.git*
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

   
