name: CI-CD-Pipeline-AWS-BeansTalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "github-actions-demo-adv-it"
  EB_APPLICATION_NAME       : "flask"
  EB_ENVIRONMENT_NAME       : "flask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"

on:
  push:
    branches:
      - master
      
      
jobs:
  ci_part:
    runs-on: ubuntu-latest
    
    steps:
# clone git repo
    - name: git clone repo
      uses: actions/checkout@v1

#archive deploy artifact exclude (-x) *.git*
    - name: create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

# granted access to aws
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key        : ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}

#copy artifact to s3
    - name: copy deployment package
      run:  aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      
    - name: finish message
      run: echo "finish message"
    
   
